### PR TITLE
Add author copyright to footer.

### PR DESCRIPTION
**Pull request by breitenb**
Hi, just a one-line change.

### CODE REVIEW

**Comment by GHLandy** [comment]
I think it better to make the author copyright as a hyperlink to his/her github as follow: 

image

**Comment by breitenb** [comment]
I see your point, but I am looking at using this template to publish a blog that will include some of my fiction.  US law says I have to to it as &copy; (year of first publication) (my name) 
https://en.wikipedia.org/wiki/Copyright_notice#Form_of_notice_for_visually_perceptible_copies

**Comment by breitenb** [comment]
Also, I was not planning on posting my Github on this site, because that is unrelated to my fiction writing.

**Comment by klugjo** [comment]
merged. thanks !

**Comment by breitenb** [comment]
Thank you!

**Pull request merged**
