### PR TITLE
Layout for pages

### PR DESCRIPTION
**Pull request by rodrigouroz**
Hi

I created a layout for pages where there's no author nor date in the heading (I use _pages_ to structure the blog with static content and I don't want those pages to be displayed as a blog post.

If you think it's useful I'll be glad with the merge.

Thanks for the work.

Rod

### CODE REVIEW

**Comment by klugjo** [comment]
I can't merge this, because it introduces too many breaking changes for existing users of the theme.

Let me see what I can do and I will come back to you in a few days

**Comment by rodrigouroz** [comment]
I understand, I just did something that was useful to me and wanted to share it in case it was useful to other people too, but of course it shouldn't break existing installations.

Let me know if I can be of any help.

**Comment by klugjo** [comment]
Thanks for supporting the theme and proposing your changes, I really appreciate it :)

I will try to achieve the same results as you using some configuration variables so that it does not affect users currently using the theme.

I will let you know once I am done so you let me know if that's what you wanted. Kind of busy with work at the moment, so it might take a few days.

Cheers,

**Comment by rodrigouroz** [comment]
Sure, there's no rush.

In case you want to check the actual result: https://rodrigouroz.github.io

I just started a blog and needed to create an "About" page but it was being shown as an article. Perhaps I was doing something wrong.

**Pull request closed without merging**
